mdapioutput/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CompanyLogo__c</fullName>
        <formula>Account.Company_Logo__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CompanyLogo</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Rep</label>
        <referenceTo>SalesReps__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

mdapioutput/classes/OppController.cls
public with sharing class OppController {
    
    @AuraEnabled
    public static List<Opportunity> findAll()
    {
        return [SELECT Id, name FROM Opportunity LIMIT 50];
    }

    @AuraEnabled
    public static List<Opportunity> findClosedWonOppsByRepName(String repName)
    {
        System.debug('In function...');
        System.debug('rep' + repName);

        List<Opportunity>allOpps = [SELECT Id,Name,Sales_Rep__c,CompanyLogo__c,StageName,Amount FROM Opportunity WHERE Sales_Rep__c = : repName];

        System.debug(allOpps);

        return allOpps;
    }


}