mdapioutput/objects/SalesReps__c.object
<CustomObject>
    <label>SalesRep</label>
    <nameField>
        <label>SalesReps Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SalesReps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>ProfilePic__c</fullName>
        <label>ProfilePic</label>
        <type>Url</type>
    </fields>
</CustomObject>

mdapioutput/classes/RepController.cls
public with sharing class RepController {
   
       @AuraEnabled
    public static List<SalesReps__c> findAll()
    {
        return [SELECT Id, name, ProfilePic__c FROM SalesReps__c LIMIT 50];
    }

      @AuraEnabled
    public static List<SalesReps__c> findRepsByName(String searchKey)
    {
    System.debug('search log' + searchKey);
    String searchInput = '%' + searchKey +'%';
        return [SELECT Id, name, ProfilePic__c FROM SalesReps__c WHERE name LIKE : searchInput LIMIT 50]; 
    }
    
}